apiVersion: apps/v1
kind: Deployment
metadata:
  name: amenity-app
  labels:
    app: amenity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amenity
  template:
    metadata:
      labels:
        app: amenity
    spec:
      containers:
      - name: amenity
        image: riocodes/amenity:1.0 
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DATABASE_HOST
          value: 192.168.66.9
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: amenity-secrets
              key: database-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: amenity-secrets
              key: database-password
        - name: DATABASE_NAME
          value: "amenity_production"
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: amenity-secrets
              key: rails-master-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10